### ISSUE TITLE
Add Headless Option

### ISSUE THREAD

**Issue by joshgreaves** [BYU-PCCL/holodeck#135]
Currently, running holodeck on a machine you are ssh'd into will run headless, but we don't have that option on a local machine. We want to be able to run holodeck without ever displaying the window, if desired.

**Comment by jaydenmilne** [comment]
According to [this answer](https://answers.unrealengine.com/questions/815764/in-the-release-notes-it-says-the-engine-can-now-cr.html?sort=oldest) if you unset the `DISPLAY` variable Unreal Engine on Linux will run headless locally. Needs to be tested with Holodeck.

Doing this on Windows might be more tricky, since in the [release notes for UE 4.14](https://docs.unrealengine.com/en-us/Support/Builds/ReleaseNotes/2016/4_14) it under the Linux section says
> New: Added "offscreen" video driver to SDL so the engine can now create GL context on headless machines not running any display servers (EGL is enough).

For me this implies that this is a feature specifically for a headless Linux environment and might not work as well on Windows.
