### ISSUE TITLE
Loading map in unreal engine failed [holodeck-engine]

### ISSUE THREAD

**Issue by insooneelife** [BYU-PCCL/holodeck#342]
**Describe the bug**

I followed all requirements on README.md file, but failed.
Error message after open holodeck.uproject file.

"Failed to load map!
../holodeck-engine/Content/ExampleLevel.umap appears to be an asset file."

**To Reproduce**
Please provide sample code to reproduce the bug.

Just clone the project and follow the manual.

**Expected behavior**

I expect the level loaded successfully on unreal engine.

**Screenshots**

**Version Information:**
Window 10

Unreal engine 4.22

 - Holodeck Version
holodeck-engine[master]

 - World/Scenario version

**Additional context**

**Comment by jaydenmilne** [comment]
`.uasset` files are stored in git-lfs. From the error you are describing, it seems git-lfs has not converted the pointer file into the actual file. Make sure git-lfs is installed and working on your machine.

Try running `git lfs pull`, or cloning with the https url instead of git.

To verify this I cloned `holodeck-engine` and disabled git-lfs and got the same error:
![image](https://user-images.githubusercontent.com/7662768/68325582-f2f54780-0086-11ea-9020-ba767b5878bc.png)

**Comment by jaydenmilne** [comment]
FYI, most of the assets that we show in our marketing stuff aren't included in `holodeck-engine` for licensing reasons.
